version: "3.8"
services:
  frontendcreadores:
    container_name: frontendcreadores
    build:
      context: .
      dockerfile: Dockerfile
      target: serve-frontendcreadores
    ports:
      - "3001:80"
    networks:
      - blitzvideo-api_default

networks:
  blitzvideo-api_default:
    external: true

