version: "3.8"
services:
  frontendcreadores:
    image: creador
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    networks:
      - blitzvideo-api_default

networks:
  blitzvideo-api_default:
    external: true

